create table employees (
	id serial primary key,
	employee_name varchar(50) not null
);

insert into employees 
values (default, 'Мария Семенова'),
	   (default, 'Федор Степанов'),
	   (default, 'Регина Авдеева'),
	   (default, 'Мария Бодрова'),
	   (default, 'Петр Дубровин'),
	   (default, 'Юлия Бойко'),
	   (default, 'Дарья Алешина'),
	   (default, 'Кирилл Бубенок'),
	   (default, 'Андрей Быков'),
	   (default, 'Юлия Гайдабас'),
	   (default, 'Анастасия Гузлова'),
	   (default, 'Александра Дармограй'),
	   (default, 'Игорь Ермаков'),
	   (default, 'Камила Жумагали'),
	   (default, 'Марина Зверева'),
	   (default, 'Екатерина Коваленко'),
	   (default, 'Дарья Козловская'),
	   (default, 'Анастасия Корнет'),
	   (default, 'Вадим Кретов'),
	   (default, 'Мария Лейбина'),
	   (default, 'София Лунгу'),
	   (default, 'Полина Мизева'),
	   (default, 'Алена Михальченкова'),
	   (default, 'Анастасия Пронина'),
	   (default, 'Мария Руденко'),
	   (default, 'Екатерина Рыбакова'),
	   (default, 'София Савоничева'),
	   (default, 'Маргарита Тимошкина'),
	   (default, 'Марина Шведова'),
	   (default, 'Виктория Шишковская'),
	   (default, 'Валерия Юрко'),
	   (default, 'Лилия Винтовкина'),
	   (default, 'Валерия Петрунина'),
	   (default, 'Николай Звягин'),
	   (default, 'Данил Фролов'),
	   (default, 'Елена Чикринева'),
	   (default, 'Елена Банчеану'),
	   (default, 'Виктория Беляева'),
	   (default, 'Дарья Бочарова'),
	   (default, 'Марина Булгакова'),
	   (default, 'Надежда Джуссоева'),
	   (default, 'Дмитрий Долин'),
	   (default, 'Елизавета Калачева'),
	   (default, 'Светлана Коваль'),
	   (default, 'Милена Кожевникова'),
	   (default, 'Мария Королева'),
	   (default, 'Кудрявцева Юлия'),
	   (default, 'Елизавета Лишневская'),
	   (default, 'Марина Матвеенко'),
	   (default, 'Елена Олейникова'),
	   (default, 'Анастасия Перепелкина'),
	   (default, 'Владислав Пособчук'),
	   (default, 'Патрисия Раби'),
	   (default, 'Ева Русак'),
	   (default, 'Ксения Рыжова'),
	   (default, 'Екатерина Соколова'),
	   (default, 'Олег Степаненко'),
	   (default, 'Анастасия Талалакина'),
	   (default, 'Полина Толпеева'),
	   (default, 'Андрей Трухачев'),
	   (default, 'Екатерина Усанова'),
	   (default, 'Анастасия Цыбульская'),
	   (default, 'Юлия Чаплыгина'),
	   (default, 'Екатерина Рысцова'),
	   (default, 'Сергей Селезнев'),
	   (default, 'Александр Никишов'),
	   (default, 'Лидия Ефимова'),
	   (default, 'Наталья Трошина'),
	   (default, 'Елена Кротова'),
	   (default, 'Вячеслав Арутюнян'),
	   (default, 'Григорий Балашов');
	 
create table salary (
	id serial primary key,
	monthly_salary int not null
);

insert into salary 
values (default, 1000),
	   (default, 1100),
	   (default, 1200),
	   (default, 1300),
	   (default, 1400),
	   (default, 1500),
	   (default, 1600),
	   (default, 1700),
	   (default, 1800),
	   (default, 1900),
	   (default, 2000),
	   (default, 2100),
	   (default, 2200),
	   (default, 2300),
	   (default, 2400),
	   (default, 2500);
	  
create table employee_salary (
		id serial primary key,
		employee_id int not null unique,
		salary_id int not null
);


insert into employee_salary 
values (default, 3, 7),
	   (default, 1, 4),
	   (default, 5, 9),
	   (default, 40, 13),
	   (default, 23, 4),
	   (default, 11, 2),
	   (default, 52, 10),
	   (default, 15, 13),
	   (default, 26, 4),
	   (default, 16, 1),
	   (default, 33, 7),
	   (default, 2, 14),
	   (default, 31, 10),
	   (default, 14, 4),
	   (default, 13, 2),
	   (default, 18, 6),
	   (default, 51, 5),
	   (default, 21, 1),
	   (default, 58, 13),
	   (default, 36, 7),
	   (default, 70, 16),
	   (default, 69, 8),
	   (default, 29, 13),
	   (default, 39, 7),
	   (default, 49, 5),
	   (default, 59, 4),
	   (default, 9, 12),
	   (default, 22, 3),
	   (default, 38, 2),
	   (default, 42, 11),
	   (default, 90, 13),
	   (default, 120, 2),
	   (default, 88, 6),
	   (default, 95, 1),
	   (default, 99, 12),
	   (default, 124, 9),
	   (default, 128, 4),
	   (default, 89, 2),
	   (default, 93, 7),
	   (default, 111, 10);
	   
	  
create table roles (
		id serial primary key,
		role_name int not null unique
);

alter table roles 
alter column role_name type varchar(30)
using role_name::varchar;

insert into roles
values (default, 'Junior Python developer'),
	   (default, 'Middle Python developer'),
	   (default, 'Senior Python developer'),
	   (default, 'Junior Java developer'),
	   (default, 'Middle Java developer'),
	   (default, 'Senior Java developer'),
	   (default, 'Junior JavaScript developer'),
	   (default, 'Middle JavaScript developer'),
	   (default, 'Senior JavaScript developer'),
	   (default, 'Junior Manual QA engineer'),
	   (default, 'Middle Manual QA engineer'),
	   (default, 'Senior Manual QA engineer'),
	   (default, 'Project Manager'),
	   (default, 'Designer'),
	   (default, 'HR'),
	   (default, 'CEO'),
	   (default, 'Sales manager'),
	   (default, 'Junior Automation QA engineer'),
	   (default, 'Middle Automation QA engineer'),
	   (default, 'Senior Automation QA engineer');

create table roles_employee (
	id serial primary key,
	employee_id int not null unique references employees (id),
	role_id int not null  references roles (id)
);

insert into roles_employee
values (default, 3, 7),
	   (default, 1, 4),
	   (default, 5, 9),
	   (default, 40, 13),
	   (default, 23, 4),
	   (default, 11, 2),
	   (default, 52, 10),
	   (default, 15, 13),
	   (default, 26, 4),
	   (default, 16, 1),
	   (default, 33, 20),
	   (default, 2, 14),
	   (default, 31, 10),
	   (default, 14, 4),
	   (default, 13, 2),
	   (default, 18, 6),
	   (default, 51, 5),
	   (default, 21, 19),
	   (default, 58, 13),
	   (default, 36, 7),
	   (default, 70, 16),
	   (default, 69, 8),
	   (default, 29, 13),
	   (default, 39, 7),
	   (default, 49, 5),
	   (default, 59, 4),
	   (default, 9, 12),
	   (default, 22, 3),
	   (default, 38, 17),
	   (default, 42, 11),
	   (default, 17, 13),
	   (default, 44, 18),
	   (default, 54, 16),
	   (default, 71, 1),
	   (default, 60, 12),
	   (default, 30, 9),
	   (default, 45, 4),
	   (default, 50, 2),
	   (default, 10, 18),
	   (default, 8, 10);
	   
	  
select * from roles_employee;